server:
  http_listen_port: 9080
  grpc_listen_port: 0
  log_level: "info"

positions:
  filename: /run/promtail/positions.yaml

clients:
  - url: http://tasks.loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-containers
    docker_sd_configs:
#      - host: tcp://tasks.docker-socket-proxy-node:2375
#        port: 2375
#        refresh_interval: 10s
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

#    pipeline_stages:
#      - json:
#          expressions:
#            service: service_name
#
#      - labels:
#          service:

    relabel_configs:
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep

      - source_labels: [__meta_docker_container_log_path]
        target_label: __path__

      # service name (swarm)
      - source_labels: [__meta_docker_container_name]
        target_label: service

      # --- (optional) stack namespace ---
      - source_labels: [__meta_docker_container_label_com_docker_stack_namespace]
        target_label: stack

      # --- instance (container name without leading /) ---
      - source_labels: [__meta_docker_container_id]
        regex: '/(.*)'
        target_label: instance
        replacement: '$1'

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [ __meta_docker_container_id ]
        separator: ';'
        regex: '^$;(.{12}).*'
        target_label: service_instance_id
        replacement: '$1'

